backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "網站設定"
    files:
      - name: "announcements"
        label: "公告管理"
        file: "data/announcements.json"
        fields:
          - name: "announcements"
            label: "公告列表"
            widget: "list"
            fields:
              - {name: "text", label: "公告內容", widget: "string"}
              - {name: "priority", label: "優先級", widget: "select", options: ["high", "medium", "low"]}
              - {name: "active", label: "是否啟用", widget: "boolean", default: true}
              - {name: "startDate", label: "開始日期", widget: "datetime", required: false}
              - {name: "endDate", label: "結束日期", widget: "datetime", required: false}
      
      - name: "hero"
        label: "首頁輪播圖管理"
        file: "data/hero.json"
        fields:
          - name: "hero"
            label: "輪播圖設定"
            widget: "object"
            fields:
              - name: "images"
                label: "輪播圖片"
                widget: "list"
                max: 3
                fields:
                  - {name: "id", label: "ID", widget: "number"}
                  - {name: "url", label: "圖片網址", widget: "image"}
                  - {name: "alt", label: "圖片描述", widget: "string"}
                  - {name: "title", label: "主標題", widget: "string"}
                  - {name: "subtitle", label: "副標題", widget: "string"}
                  - {name: "description", label: "描述文字", widget: "text"}
                  - {name: "active", label: "啟用", widget: "boolean", default: true}
              - {name: "autoplay", label: "自動播放", widget: "boolean", default: true}
              - {name: "interval", label: "切換間隔(毫秒)", widget: "number", default: 5000}
              - {name: "showIndicators", label: "顯示指示器", widget: "boolean", default: true}
              - {name: "showNavigation", label: "顯示導航按鈕", widget: "boolean", default: true}

      - name: "notice"
        label: "重要通知管理"
        file: "data/notice.json"
        fields:
          - name: "notice"
            label: "重要通知設定"
            widget: "object"
            fields:
              - {name: "enabled", label: "啟用通知", widget: "boolean", default: true}
              - {name: "triggerText", label: "觸發按鈕文字", widget: "string", default: "重要通知"}
              - {name: "title", label: "通知標題", widget: "string"}
              - {name: "content", label: "通知內容", widget: "text"}
              - name: "type"
                label: "通知類型"
                widget: "select"
                options: ["info", "warning", "success", "error"]
                default: "info"
              - {name: "backgroundColor", label: "背景顏色", widget: "string", default: "rgba(10, 10, 10, 0.95)", required: false}
              - {name: "textColor", label: "文字顏色", widget: "string", default: "#e0e0e0", required: false}
              - {name: "borderColor", label: "邊框顏色", widget: "string", default: "#ff00ff", required: false}

      - name: "contact"
        label: "聯繫信息管理"
        file: "data/contact.json"
        fields:
          - name: "contact"
            label: "聯繫信息"
            widget: "object"
            fields:
              - {name: "email", label: "Email", widget: "string"}
              - {name: "line_id", label: "LINE ID", widget: "string"}
              - {name: "service_hours", label: "服務時間", widget: "string"}
              - {name: "telegram", label: "Telegram", widget: "string"}
              - {name: "instagram", label: "Instagram", widget: "string"}
              - {name: "facebook", label: "Facebook", widget: "string"}
      
      - name: "prices"
        label: "價格管理"
        file: "data/prices.json"
        fields:
          - name: "products"
            label: "產品價格"
            widget: "list"
            fields:
              - {name: "id", label: "產品ID", widget: "string"}
              - {name: "name", label: "產品名稱", widget: "string"}
              - {name: "price", label: "價格", widget: "number"}
              - {name: "originalPrice", label: "原價", widget: "number", required: false}
              - {name: "discount", label: "折扣", widget: "string", required: false}
              - {name: "lastUpdated", label: "更新時間", widget: "datetime", default: ""} 